# Generated by Django 3.0.2 on 2020-01-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='second_name',
            field=models.CharField(default='TestSecondName', max_length=50),
            preserve_default=False,
        ),
    ]
